# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Hosted Windows 2019 with VS2019
  demands: azureps

steps:
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Host APIM Instance'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '<AzureSubscription>'
    subscriptionId: '<AzureSubscriptionId>'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'test-rg'
    location: 'Central US'
    templateLocation: 'Linked artifact'
    csmFile: 'service.azuredeploy.template.json'
    csmParametersFile: './service.azuredeploy.parameters.json'
    deploymentMode: 'Incremental'
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Create Version-Set in the APIM instance'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '<AzureSubscription>'
    subscriptionId: '<AzureSubscriptionId>'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'test-rg'
    location: 'Central US'
    templateLocation: 'Linked artifact'
    csmFile: 'api-httpbin.version-set.template.json'
    csmParametersFile: './service.azuredeploy.parameters.json'
    deploymentMode: 'Incremental'
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Create an API in the APIM instance'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '<AzureSubscription>'
    subscriptionId: '<AzureSubscriptionId>'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'test-rg'
    location: 'Central US'
    templateLocation: 'Linked artifact'
    csmFile: 'api-httpbin.template.json'
    csmParametersFile: './service.azuredeploy.parameters.json'
    deploymentMode: 'Incremental'
